# Generated by Django 5.2.7 on 2026-01-11 15:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "products",
            "0005_rename_products_model_i_a1b2c3_idx_products_model_i_26a2e4_idx",
        ),
        ("supplier", "0003_alter_suppliercontact_name_kana_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacturing_number",
                    models.CharField(
                        help_text="制作品を識別する品番",
                        max_length=100,
                        unique=True,
                        verbose_name="品番",
                    ),
                ),
                (
                    "manufacturing_name",
                    models.CharField(max_length=200, verbose_name="制作品名"),
                ),
                (
                    "specification",
                    models.TextField(
                        blank=True, help_text="制作品の詳細仕様", verbose_name="仕様"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="個",
                        help_text="単位（個、kg、m等）",
                        max_length=20,
                        verbose_name="単位",
                    ),
                ),
                (
                    "standard_production_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="1個あたりの標準製造時間",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="標準製造時間（時間）",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="この制作品が現在使用可能かどうか",
                        verbose_name="有効",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_manufacturing_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="この制作品が紐づく製品",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manufacturing_items",
                        to="products.product",
                        verbose_name="製品",
                    ),
                ),
            ],
            options={
                "verbose_name": "制作品",
                "verbose_name_plural": "制作品一覧",
                "db_table": "manufacturing_items",
                "ordering": ["manufacturing_number"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(
                        help_text="材料を識別する品番",
                        max_length=100,
                        unique=True,
                        verbose_name="品番",
                    ),
                ),
                (
                    "material_name",
                    models.CharField(max_length=200, verbose_name="材料名"),
                ),
                (
                    "material_type",
                    models.CharField(
                        blank=True,
                        help_text="材料の形式・規格",
                        max_length=100,
                        verbose_name="形式",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("raw", "原材料"),
                            ("semi_finished", "半製品"),
                            ("component", "部品"),
                            ("consumable", "消耗品"),
                            ("other", "その他"),
                        ],
                        default="raw",
                        max_length=20,
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "specification",
                    models.TextField(
                        blank=True, help_text="材料の詳細仕様", verbose_name="仕様"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="個",
                        help_text="在庫管理単位（個、kg、m等）",
                        max_length=20,
                        verbose_name="単位",
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(
                        default=0, help_text="現在の在庫数量", verbose_name="在庫数量"
                    ),
                ),
                (
                    "minimum_stock",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="在庫警告のしきい値",
                        verbose_name="最小在庫数",
                    ),
                ),
                (
                    "maximum_stock",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="最大在庫容量",
                        null=True,
                        verbose_name="最大在庫数",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="参考単価",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="単価",
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="標準納期日数",
                        null=True,
                        verbose_name="リードタイム（日）",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="この材料が現在使用可能かどうか",
                        verbose_name="有効",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_materials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "supplier_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="supplier.supplierbranch",
                        verbose_name="仕入先支店",
                    ),
                ),
            ],
            options={
                "verbose_name": "材料",
                "verbose_name_plural": "材料一覧",
                "db_table": "materials",
                "ordering": ["material_code"],
            },
        ),
        migrations.CreateModel(
            name="ManufacturingMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_required",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="制作品1個あたりに必要な材料の数量",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="必要数量",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "manufacturing_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_requirements",
                        to="manufacturing.manufacturingitem",
                        verbose_name="制作品",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manufacturing_usages",
                        to="manufacturing.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "制作品材料構成",
                "verbose_name_plural": "制作品材料構成一覧",
                "db_table": "manufacturing_materials",
                "ordering": ["manufacturing_item", "material"],
            },
        ),
        migrations.CreateModel(
            name="MaterialDeliverySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="納入予定数量")),
                ("scheduled_date", models.DateField(verbose_name="納入予定日")),
                (
                    "actual_date",
                    models.DateField(blank=True, null=True, verbose_name="実納入日"),
                ),
                (
                    "actual_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="実納入数量"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "予定"),
                            ("ordered", "発注済み"),
                            ("in_transit", "輸送中"),
                            ("received", "受入済み"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "order_reference",
                    models.CharField(
                        blank=True,
                        help_text="関連する発注番号",
                        max_length=100,
                        verbose_name="発注番号",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_material_deliveries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_schedules",
                        to="manufacturing.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "材料納入予定",
                "verbose_name_plural": "材料納入予定一覧",
                "db_table": "material_delivery_schedules",
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="ProductionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_number",
                    models.CharField(
                        help_text="生産計画を識別する番号",
                        max_length=50,
                        unique=True,
                        verbose_name="計画番号",
                    ),
                ),
                (
                    "total_planned_quantity",
                    models.PositiveIntegerField(
                        help_text="製造予定の総数量", verbose_name="合計予定数量"
                    ),
                ),
                (
                    "completed_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="実際に完成した数量",
                        verbose_name="完成数量",
                    ),
                ),
                (
                    "planned_start_date",
                    models.DateField(blank=True, null=True, verbose_name="計画開始日"),
                ),
                (
                    "planned_end_date",
                    models.DateField(blank=True, null=True, verbose_name="計画完了日"),
                ),
                (
                    "actual_start_date",
                    models.DateField(blank=True, null=True, verbose_name="実開始日"),
                ),
                (
                    "actual_end_date",
                    models.DateField(blank=True, null=True, verbose_name="実完了日"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("planned", "計画済み"),
                            ("in_progress", "製造中"),
                            ("completed", "完了"),
                            ("cancelled", "キャンセル"),
                            ("on_hold", "保留"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="1が最高優先度",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="優先度",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_production_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "manufacturing_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_plans",
                        to="manufacturing.manufacturingitem",
                        verbose_name="制作品",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_plans",
                        to="products.product",
                        verbose_name="製品",
                    ),
                ),
            ],
            options={
                "verbose_name": "生産計画",
                "verbose_name_plural": "生産計画一覧",
                "db_table": "production_plans",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule_number",
                    models.CharField(
                        help_text="スケジュールを識別する番号",
                        max_length=50,
                        verbose_name="スケジュール番号",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="このスケジュールで製造する数量",
                        verbose_name="製造数量",
                    ),
                ),
                (
                    "completed_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="実際に完成した数量",
                        verbose_name="完成数量",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="制作開始日時"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成予定日時"
                    ),
                ),
                (
                    "actual_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="実開始日時"
                    ),
                ),
                (
                    "actual_finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="実完了日時"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "計画済み"),
                            ("in_progress", "製造中"),
                            ("completed", "完了"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "production_line",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="製造ライン"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="担当者",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_production_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="manufacturing.productionplan",
                        verbose_name="生産計画",
                    ),
                ),
            ],
            options={
                "verbose_name": "生産スケジュール",
                "verbose_name_plural": "生産スケジュール一覧",
                "db_table": "production_schedules",
                "ordering": ["started_at", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="manufacturingitem",
            index=models.Index(
                fields=["manufacturing_number"], name="manufacturi_manufac_2ce60b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manufacturingitem",
            index=models.Index(
                fields=["product", "is_active"], name="manufacturi_product_a780ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manufacturingitem",
            index=models.Index(
                fields=["is_active"], name="manufacturi_is_acti_527d47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manufacturingitem",
            index=models.Index(
                fields=["created_at"], name="manufacturi_created_13ec81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["material_code"], name="materials_materia_14fe81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["material_type"], name="materials_materia_728bd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["category"], name="materials_categor_183e9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["is_active"], name="materials_is_acti_c341ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["supplier_branch"], name="materials_supplie_48270b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["stock_quantity"], name="materials_stock_q_81e1ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["created_at"], name="materials_created_65e81e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manufacturingmaterial",
            index=models.Index(
                fields=["manufacturing_item"], name="manufacturi_manufac_36eafd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manufacturingmaterial",
            index=models.Index(
                fields=["material"], name="manufacturi_materia_28b3a8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="manufacturingmaterial",
            unique_together={("manufacturing_item", "material")},
        ),
        migrations.AddIndex(
            model_name="materialdeliveryschedule",
            index=models.Index(
                fields=["material"], name="material_de_materia_12bfe3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialdeliveryschedule",
            index=models.Index(
                fields=["scheduled_date"], name="material_de_schedul_5bea96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialdeliveryschedule",
            index=models.Index(fields=["status"], name="material_de_status_bf6001_idx"),
        ),
        migrations.AddIndex(
            model_name="materialdeliveryschedule",
            index=models.Index(
                fields=["material", "status"], name="material_de_materia_675f45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionplan",
            index=models.Index(
                fields=["plan_number"], name="production__plan_nu_d6a774_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionplan",
            index=models.Index(
                fields=["manufacturing_item", "status"],
                name="production__manufac_a45d81_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productionplan",
            index=models.Index(
                fields=["product", "status"], name="production__product_c1de79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionplan",
            index=models.Index(fields=["status"], name="production__status_3669c1_idx"),
        ),
        migrations.AddIndex(
            model_name="productionplan",
            index=models.Index(
                fields=["planned_start_date"], name="production__planned_11b8a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionplan",
            index=models.Index(
                fields=["planned_end_date"], name="production__planned_1096fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionplan",
            index=models.Index(
                fields=["priority"], name="production__priorit_4292e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionschedule",
            index=models.Index(fields=["plan"], name="production__plan_id_454e8c_idx"),
        ),
        migrations.AddIndex(
            model_name="productionschedule",
            index=models.Index(
                fields=["schedule_number"], name="production__schedul_f1f827_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionschedule",
            index=models.Index(fields=["status"], name="production__status_0c2d63_idx"),
        ),
        migrations.AddIndex(
            model_name="productionschedule",
            index=models.Index(
                fields=["started_at"], name="production__started_47e09e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionschedule",
            index=models.Index(
                fields=["finished_at"], name="production__finishe_f92605_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionschedule",
            index=models.Index(
                fields=["assigned_to"], name="production__assigne_b1d99a_idx"
            ),
        ),
    ]
