# Generated by Django migration
# api/manufacturing/migrations/0002_add_production_type_to_manufacturing_item.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingitem',
            name='production_type',
            field=models.CharField(
                choices=[('domestic', '国内生産'), ('overseas', '海外生産')],
                default='domestic',
                help_text='国内生産または海外生産',
                max_length=20,
                verbose_name='生産タイプ'
            ),
        ),
        migrations.AddIndex(
            model_name='manufacturingitem',
            index=models.Index(fields=['production_type'], name='manufacturi_product_a8c7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturingitem',
            index=models.Index(fields=['production_type', 'is_active'], name='manufacturi_product_3d8f12_idx'),
        ),
    ]
