# Generated by Django 5.2.7 on 2026-01-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0002_add_production_type_to_manufacturing_item"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="manufacturingitem",
            new_name="manufacturi_product_f47202_idx",
            old_name="manufacturi_product_a8c7e4_idx",
        ),
        migrations.RenameIndex(
            model_name="manufacturingitem",
            new_name="manufacturi_product_8ffe26_idx",
            old_name="manufacturi_product_3d8f12_idx",
        ),
    ]
