# Generated by Django 5.2.7 on 2026-01-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manufacturing",
            "0003_rename_manufacturi_product_a8c7e4_idx_manufacturi_product_f47202_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturingitem",
            name="production_type",
            field=models.CharField(
                choices=[
                    ("domestic", "国内生産"),
                    ("overseas", "海外生産"),
                    ("both", "国内・海外両方"),
                ],
                default="domestic",
                help_text="国内生産または海外生産",
                max_length=20,
                verbose_name="生産タイプ",
            ),
        ),
    ]
