# Generated by Django 5.2.7 on 2026-01-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0005_add_overseas_supplier_branch"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="manufacturingitem",
            new_name="manufacturi_oversea_f99f02_idx",
            old_name="manufacturing_overseas_idx",
        ),
    ]
