# Generated by Django 5.2.7 on 2026-01-30 15:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manufacturing",
            "0006_rename_manufacturing_overseas_idx_manufacturi_oversea_f99f02_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingitem",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="海外サプライヤーからの仕入れ単価（海外生産の場合）",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="仕入れ単価",
            ),
        ),
    ]
