# Generated by Django 5.2.7 on 2026-02-01 14:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0007_manufacturingitem_purchase_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturingItemPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="税抜単価",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="単価",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="この価格が有効になる日", verbose_name="開始日"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="この価格が無効になる日（空白の場合は無期限）",
                        null=True,
                        verbose_name="終了日",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="この価格履歴が有効かどうか",
                        verbose_name="有効",
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(
                        blank=True, help_text="価格変更の理由", verbose_name="変更理由"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_manufacturing_item_price_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "manufacturing_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manufacturing_item_price_histories",
                        to="manufacturing.manufacturingitem",
                        verbose_name="製造品",
                    ),
                ),
            ],
            options={
                "verbose_name": "製造品価格履歴",
                "verbose_name_plural": "製造品価格履歴一覧",
                "db_table": "manufacturing_item_price_histories",
                "ordering": ["-start_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["manufacturing_item"],
                        name="manufacturi_manufac_449dd3_idx",
                    ),
                    models.Index(
                        fields=["start_date"], name="manufacturi_start_d_8960f6_idx"
                    ),
                    models.Index(
                        fields=["end_date"], name="manufacturi_end_dat_2dbb8f_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="manufacturi_is_acti_a185cd_idx"
                    ),
                    models.Index(
                        fields=["manufacturing_item", "is_active"],
                        name="manufacturi_manufac_9f2ae5_idx",
                    ),
                    models.Index(
                        fields=["manufacturing_item", "start_date"],
                        name="manufacturi_manufac_60f2f2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MaterialPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="税抜単価",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="単価",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="この価格が有効になる日", verbose_name="開始日"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="この価格が無効になる日（空白の場合は無期限）",
                        null=True,
                        verbose_name="終了日",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="この価格履歴が有効かどうか",
                        verbose_name="有効",
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(
                        blank=True, help_text="価格変更の理由", verbose_name="変更理由"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_material_price_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_price_histories",
                        to="manufacturing.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "材料価格履歴",
                "verbose_name_plural": "材料価格履歴一覧",
                "db_table": "material_price_histories",
                "ordering": ["-start_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["material"], name="material_pr_materia_053495_idx"
                    ),
                    models.Index(
                        fields=["start_date"], name="material_pr_start_d_af0b5e_idx"
                    ),
                    models.Index(
                        fields=["end_date"], name="material_pr_end_dat_0a6f94_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="material_pr_is_acti_1bae92_idx"
                    ),
                    models.Index(
                        fields=["material", "is_active"],
                        name="material_pr_materia_9e5482_idx",
                    ),
                    models.Index(
                        fields=["material", "start_date"],
                        name="material_pr_materia_29953d_idx",
                    ),
                ],
            },
        ),
    ]
