# Generated by Django 5.2.7 on 2025-11-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0003_alter_part_lead_time_days_alter_part_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("MOQ", "最低発注数量"),
                    ("SPQ", "標準梱包数量"),
                    ("SNP", "出荷梱包数量"),
                    ("OTHER", "その他"),
                ],
                default="MOQ",
                max_length=20,
                verbose_name="発注区分",
            ),
        ),
    ]
