# Generated by Django 5.2.7 on 2025-11-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0004_part_order_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="supplier_part_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="仕入先部品名称"
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("MOQ", "MOQ"),
                    ("SPQ", "SPQ"),
                    ("SNP", "SNP"),
                    ("OTHER", "その他"),
                ],
                default="MOQ",
                max_length=20,
                verbose_name="発注区分",
            ),
        ),
    ]
