# Generated by Django 5.2.7 on 2025-12-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0006_part_quantity_per_product_supplieditem"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="supplieditem",
            new_name="supplied_it_item_nu_42be0d_idx",
            old_name="supplied_it_item_nu_idx",
        ),
        migrations.RenameIndex(
            model_name="supplieditem",
            new_name="supplied_it_product_a01e48_idx",
            old_name="supplied_it_product_idx",
        ),
        migrations.RenameIndex(
            model_name="supplieditem",
            new_name="supplied_it_created_a1fdcb_idx",
            old_name="supplied_it_created_idx",
        ),
    ]
