# Generated by Django 5.2.7 on 2025-12-16 13:30

import api.purchases.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchases",
            "0007_rename_supplied_it_item_nu_idx_supplied_it_item_nu_42be0d_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplieditem",
            name="quantity_per_product",
        ),
        migrations.AddField(
            model_name="part",
            name="usage_quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="製品1個あたりの使用数量",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="使用数",
            ),
        ),
        migrations.AddField(
            model_name="supplieditem",
            name="standard_quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="製品1個あたりの標準使用数量",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="標準数量",
            ),
        ),
        migrations.AlterField(
            model_name="supplieditem",
            name="item_name",
            field=models.CharField(max_length=200, verbose_name="支給品名"),
        ),
        migrations.AlterField(
            model_name="supplieditem",
            name="item_number",
            field=models.CharField(
                help_text="支給品を識別する品番",
                max_length=100,
                verbose_name="支給品品番",
            ),
        ),
        migrations.AlterField(
            model_name="supplieditem",
            name="unit",
            field=models.CharField(
                default="個",
                help_text="単位（個、kg、m等）",
                max_length=20,
                verbose_name="単位",
            ),
        ),
        migrations.CreateModel(
            name="SuppliedItemPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="税抜単価",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="単価",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="この価格が有効になる日", verbose_name="開始日"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="この価格が無効になる日（空白の場合は無期限）",
                        null=True,
                        verbose_name="終了日",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="手動で無効化する場合に使用",
                        verbose_name="有効",
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(
                        blank=True,
                        help_text="価格変更の理由や背景",
                        verbose_name="変更理由",
                    ),
                ),
                (
                    "quote_file",
                    models.FileField(
                        blank=True,
                        help_text="見積書のPDFやExcelファイル",
                        max_length=500,
                        null=True,
                        upload_to=api.purchases.models.supplied_item_quote_file_upload_path,
                        verbose_name="見積書ファイル",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_supplied_item_price_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "supplied_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplied_item_price_histories",
                        to="purchases.supplieditem",
                        verbose_name="支給品",
                    ),
                ),
            ],
            options={
                "verbose_name": "支給品価格履歴",
                "verbose_name_plural": "支給品価格履歴一覧",
                "db_table": "supplied_item_price_histories",
                "ordering": ["-start_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["supplied_item", "start_date"],
                        name="supplied_it_supplie_a59d25_idx",
                    ),
                    models.Index(
                        fields=["supplied_item", "is_active"],
                        name="supplied_it_supplie_4f37ff_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="supplied_it_start_d_df1c28_idx",
                    ),
                ],
            },
        ),
    ]
