# Generated by Django 5.2.7 on 2025-12-17 15:50

import api.purchases.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("purchases", "0009_remove_supplieditemprice_quote_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuppliedItemList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "list_number",
                    models.CharField(
                        help_text="支給品リストを識別する番号",
                        max_length=50,
                        unique=True,
                        verbose_name="リスト番号",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        help_text="支給品の納品予定日", verbose_name="納品予定日"
                    ),
                ),
                (
                    "csv_file",
                    models.FileField(
                        blank=True,
                        help_text="インポート元のCSVファイル",
                        null=True,
                        upload_to=api.purchases.models.supplied_item_list_file_upload_path,
                        verbose_name="CSVファイル",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("pending_receiving", "受入待ち"),
                            ("receiving", "受入中"),
                            ("pending_count", "員数確認待ち"),
                            ("counting", "員数確認中"),
                            ("completed", "完了"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_supplied_item_lists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplied_item_lists",
                        to="customers.customer",
                        verbose_name="取引先",
                    ),
                ),
            ],
            options={
                "verbose_name": "支給品リスト",
                "verbose_name_plural": "支給品リスト一覧",
                "db_table": "supplied_item_lists",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SuppliedItemListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_number", models.CharField(max_length=100, verbose_name="品番")),
                ("item_name", models.CharField(max_length=200, verbose_name="品名")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="リストに記載された数量", verbose_name="数量"
                    ),
                ),
                (
                    "quantity_per_box",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="1箱あたりの入数",
                        null=True,
                        verbose_name="入数",
                    ),
                ),
                (
                    "box_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="箱数"
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="個", max_length=20, verbose_name="単位"),
                ),
                (
                    "receiving_confirmed",
                    models.BooleanField(default=False, verbose_name="受入確認済み"),
                ),
                (
                    "receiving_confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="受入確認日時"
                    ),
                ),
                (
                    "received_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="実際に受け入れた数量",
                        null=True,
                        verbose_name="受入数量",
                    ),
                ),
                (
                    "count_confirmed",
                    models.BooleanField(default=False, verbose_name="員数確認済み"),
                ),
                (
                    "count_confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="員数確認日時"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "count_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="count_confirmed_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="員数確認者",
                    ),
                ),
                (
                    "receiving_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receiving_confirmed_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="受入確認者",
                    ),
                ),
                (
                    "supplied_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="list_items",
                        to="purchases.supplieditem",
                        verbose_name="支給品マスタ",
                    ),
                ),
                (
                    "supplied_item_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchases.supplieditemlist",
                        verbose_name="支給品リスト",
                    ),
                ),
            ],
            options={
                "verbose_name": "支給品リスト項目",
                "verbose_name_plural": "支給品リスト項目一覧",
                "db_table": "supplied_item_list_items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SuppliedItemInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="在庫数量")),
                (
                    "lot_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ロット番号"
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="入庫日"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_inventories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "supplied_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventories",
                        to="purchases.supplieditem",
                        verbose_name="支給品",
                    ),
                ),
                (
                    "list_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventories",
                        to="purchases.supplieditemlistitem",
                        verbose_name="リスト項目",
                    ),
                ),
            ],
            options={
                "verbose_name": "支給品在庫",
                "verbose_name_plural": "支給品在庫一覧",
                "db_table": "supplied_item_inventories",
                "ordering": ["-received_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SuppliedItemReceiving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "一時保存"), ("completed", "完了")],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "receiving_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="受入日時"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_receivings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "supplied_item_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receivings",
                        to="purchases.supplieditemlist",
                        verbose_name="支給品リスト",
                    ),
                ),
            ],
            options={
                "verbose_name": "支給品受入確認",
                "verbose_name_plural": "支給品受入確認一覧",
                "db_table": "supplied_item_receivings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SuppliedItemReceivingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_number", models.CharField(max_length=100, verbose_name="品番")),
                (
                    "quantity_per_box",
                    models.PositiveIntegerField(
                        help_text="1箱あたりの入数", verbose_name="入数"
                    ),
                ),
                ("box_count", models.PositiveIntegerField(verbose_name="箱数")),
                (
                    "calculated_quantity",
                    models.PositiveIntegerField(
                        help_text="入数 × 箱数で自動計算", verbose_name="数量"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "list_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receiving_items",
                        to="purchases.supplieditemlistitem",
                        verbose_name="リスト項目",
                    ),
                ),
                (
                    "receiving",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchases.supplieditemreceiving",
                        verbose_name="受入確認",
                    ),
                ),
            ],
            options={
                "verbose_name": "支給品受入確認項目",
                "verbose_name_plural": "支給品受入確認項目一覧",
                "db_table": "supplied_item_receiving_items",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="supplieditemlist",
            index=models.Index(
                fields=["list_number"], name="supplied_it_list_nu_34a1af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemlist",
            index=models.Index(
                fields=["customer", "status"], name="supplied_it_custome_931159_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemlist",
            index=models.Index(
                fields=["delivery_date"], name="supplied_it_deliver_c8eda3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemlist",
            index=models.Index(fields=["status"], name="supplied_it_status_174369_idx"),
        ),
        migrations.AddIndex(
            model_name="supplieditemlistitem",
            index=models.Index(
                fields=["supplied_item_list"], name="supplied_it_supplie_8083c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemlistitem",
            index=models.Index(
                fields=["item_number"], name="supplied_it_item_nu_4e79ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemlistitem",
            index=models.Index(
                fields=["receiving_confirmed"], name="supplied_it_receivi_e18206_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemlistitem",
            index=models.Index(
                fields=["count_confirmed"], name="supplied_it_count_c_3ae7b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="suppliediteminventory",
            index=models.Index(
                fields=["supplied_item"], name="supplied_it_supplie_4a1c43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="suppliediteminventory",
            index=models.Index(
                fields=["lot_number"], name="supplied_it_lot_num_42254e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="suppliediteminventory",
            index=models.Index(
                fields=["received_date"], name="supplied_it_receive_89e5fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemreceiving",
            index=models.Index(
                fields=["supplied_item_list"], name="supplied_it_supplie_b64e6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemreceiving",
            index=models.Index(fields=["status"], name="supplied_it_status_96d16b_idx"),
        ),
        migrations.AddIndex(
            model_name="supplieditemreceiving",
            index=models.Index(
                fields=["receiving_date"], name="supplied_it_receivi_28e2e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemreceivingitem",
            index=models.Index(
                fields=["receiving"], name="supplied_it_receivi_d19542_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemreceivingitem",
            index=models.Index(
                fields=["item_number"], name="supplied_it_item_nu_9bfa44_idx"
            ),
        ),
    ]
