# Generated by Django 5.2.7 on 2025-12-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0011_rebuild_supplieditemlist_for_product"),
    ]

    # operations = [
    #     migrations.RemoveIndex(
    #         model_name="supplieditemlist",
    #         name="supplied_it_custome_931159_idx",
    #     ),
    #     migrations.RemoveIndex(
    #         model_name="supplieditemlist",
    #         name="supplied_it_list_nu_7a1b2c_idx",
    #     ),
    #     migrations.RemoveIndex(
    #         model_name="supplieditemlist",
    #         name="supplied_it_deliver_9j0k1l_idx",
    #     ),
    #     migrations.RemoveIndex(
    #         model_name="supplieditemlist",
    #         name="supplied_it_status_2m3n4o_idx",
    #     ),
    #     migrations.RenameIndex(
    #         model_name="supplieditemlist",
    #         new_name="supplied_it_product_5e9d47_idx",
    #         old_name="supplied_it_product_3d4e5f_idx",
    #     ),
    #     migrations.RenameIndex(
    #         model_name="supplieditemlist",
    #         new_name="supplied_it_issue_d_2e1efc_idx",
    #         old_name="supplied_it_issue_d_6g7h8i_idx",
    #     ),
    # ]
