# Generated by Django 5.2.7 on 2025-12-18 16:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_customer_product_customer_branch_and_more"),
        (
            "purchases",
            "0012_remove_supplieditemlist_supplied_it_custome_931159_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="supplieditemlist",
            name="supplied_it_custome_931159_idx",
        ),
        migrations.RemoveField(
            model_name="supplieditemlist",
            name="customer",
        ),
        migrations.AddField(
            model_name="supplieditemlist",
            name="issue_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="CSVの発行日（1列目）",
                verbose_name="発行日",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplieditemlist",
            name="product",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplied_item_lists",
                to="products.product",
                verbose_name="製品",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supplieditemlist",
            name="delivery_date",
            field=models.DateField(
                blank=True,
                help_text="支給品の納品予定日",
                null=True,
                verbose_name="納品予定日",
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemlist",
            index=models.Index(
                fields=["product", "status"], name="supplied_it_product_5e9d47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemlist",
            index=models.Index(
                fields=["issue_date"], name="supplied_it_issue_d_2e1efc_idx"
            ),
        ),
    ]
