# Generated by Django 5.2.7 on 2025-12-23 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0005_rename_products_model_i_a1b2c3_idx_products_model_i_26a2e4_idx",
        ),
        (
            "purchases",
            "0013_remove_supplieditemlist_supplied_it_custome_931159_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supplieditemreceiving",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplied_item_receivings",
                to="products.product",
                verbose_name="製品",
            ),
        ),
        migrations.AddField(
            model_name="supplieditemreceivingitem",
            name="item_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="品名"
            ),
        ),
        migrations.AddField(
            model_name="supplieditemreceivingitem",
            name="supplied_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receiving_items",
                to="purchases.supplieditem",
                verbose_name="支給品マスタ",
            ),
        ),
        migrations.AlterField(
            model_name="supplieditemreceiving",
            name="supplied_item_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receivings",
                to="purchases.supplieditemlist",
                verbose_name="支給品リスト",
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemlistitem",
            index=models.Index(
                fields=["supplied_item_list", "count_confirmed"],
                name="supplied_it_supplie_fa3d82_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemlistitem",
            index=models.Index(
                fields=["supplied_item_list", "receiving_confirmed"],
                name="supplied_it_supplie_3e20ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemreceiving",
            index=models.Index(
                fields=["product"], name="supplied_it_product_cb376e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemreceiving",
            index=models.Index(
                fields=["product", "status"], name="supplied_it_product_df592e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemreceiving",
            index=models.Index(
                fields=["supplied_item_list", "status"],
                name="supplied_it_supplie_5413b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplieditemreceivingitem",
            index=models.Index(
                fields=["receiving", "item_number"],
                name="supplied_it_receivi_32ac82_idx",
            ),
        ),
    ]
