# Generated by Django 4.2 on 2025-12-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_remove_supplieditemlist_supplied_it_custome_931159_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieditemreceiving',
            name='supplied_item_lists',
            field=models.ManyToManyField(blank=True, related_name='multi_receivings', to='purchases.supplieditemlist', verbose_name='支給品リスト（複数）'),
        ),
        migrations.AlterField(
            model_name='supplieditemreceiving',
            name='supplied_item_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='receivings', to='purchases.supplieditemlist', verbose_name='支給品リスト（単一）'),
        ),
    ]
