# Generated by Django 5.2.7 on 2025-12-26 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0014_supplieditemreceiving_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplieditemreceiving",
            name="supplied_item_lists",
            field=models.ManyToManyField(
                blank=True,
                related_name="multi_receivings",
                to="purchases.supplieditemlist",
                verbose_name="支給品リスト（複数）",
            ),
        ),
        migrations.AlterField(
            model_name="supplieditemreceiving",
            name="supplied_item_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receivings",
                to="purchases.supplieditemlist",
                verbose_name="支給品リスト（単一）",
            ),
        ),
    ]
