# Generated by Django 5.2.7 on 2025-12-29 06:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0005_rename_products_model_i_a1b2c3_idx_products_model_i_26a2e4_idx",
        ),
        ("purchases", "0015_supplieditemreceiving_supplied_item_lists_and_more"),
        ("supplier", "0003_alter_suppliercontact_name_kana_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        help_text="発注を識別する番号",
                        max_length=50,
                        unique=True,
                        verbose_name="発注番号",
                    ),
                ),
                (
                    "order_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="発注日"
                    ),
                ),
                (
                    "requested_delivery_date",
                    models.DateField(blank=True, null=True, verbose_name="希望納期"),
                ),
                (
                    "confirmed_delivery_date",
                    models.DateField(blank=True, null=True, verbose_name="確定納期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("ordered", "発注済み"),
                            ("partially_received", "一部受入"),
                            ("received", "受入完了"),
                            ("pending_count", "員数確認待ち"),
                            ("counting", "員数確認中"),
                            ("completed", "完了"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="products.product",
                        verbose_name="製品",
                    ),
                ),
                (
                    "supplier_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="supplier.supplierbranch",
                        verbose_name="仕入先支店",
                    ),
                ),
            ],
            options={
                "verbose_name": "発注",
                "verbose_name_plural": "発注一覧",
                "db_table": "purchase_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_number",
                    models.CharField(max_length=100, verbose_name="部品品番"),
                ),
                ("part_name", models.CharField(max_length=200, verbose_name="部品名")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="発注数量", verbose_name="発注数量"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="発注時の単価",
                        max_digits=12,
                        null=True,
                        verbose_name="単価",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="金額",
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="個", max_length=20, verbose_name="単位"),
                ),
                (
                    "receiving_confirmed",
                    models.BooleanField(default=False, verbose_name="受入確認済み"),
                ),
                (
                    "receiving_confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="受入確認日時"
                    ),
                ),
                (
                    "received_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="実際に受け入れた数量",
                        null=True,
                        verbose_name="受入数量",
                    ),
                ),
                (
                    "count_confirmed",
                    models.BooleanField(default=False, verbose_name="員数確認済み"),
                ),
                (
                    "count_confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="員数確認日時"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "count_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="count_confirmed_purchase_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="員数確認者",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_items",
                        to="purchases.part",
                        verbose_name="部品",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchases.purchaseorder",
                        verbose_name="発注",
                    ),
                ),
                (
                    "receiving_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receiving_confirmed_purchase_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="受入確認者",
                    ),
                ),
            ],
            options={
                "verbose_name": "発注明細",
                "verbose_name_plural": "発注明細一覧",
                "db_table": "purchase_order_items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PurchasedItemInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="在庫数量")),
                (
                    "lot_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ロット番号"
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="入庫日"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_purchased_item_inventories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventories",
                        to="purchases.part",
                        verbose_name="部品",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventories",
                        to="purchases.purchaseorderitem",
                        verbose_name="発注明細",
                    ),
                ),
            ],
            options={
                "verbose_name": "購入品在庫",
                "verbose_name_plural": "購入品在庫一覧",
                "db_table": "purchased_item_inventories",
                "ordering": ["-received_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReceiving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "一時保存"), ("completed", "完了")],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "receiving_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="受入日時"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_purchase_receivings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_receivings",
                        to="products.product",
                        verbose_name="製品",
                    ),
                ),
                (
                    "purchase_orders",
                    models.ManyToManyField(
                        blank=True,
                        related_name="receivings",
                        to="purchases.purchaseorder",
                        verbose_name="発注",
                    ),
                ),
                (
                    "supplier_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_receivings",
                        to="supplier.supplierbranch",
                        verbose_name="仕入先支店",
                    ),
                ),
            ],
            options={
                "verbose_name": "購入品受入確認",
                "verbose_name_plural": "購入品受入確認一覧",
                "db_table": "purchase_receivings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReceivingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_number",
                    models.CharField(max_length=100, verbose_name="部品品番"),
                ),
                (
                    "part_name",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="部品名"
                    ),
                ),
                (
                    "quantity_per_box",
                    models.PositiveIntegerField(
                        help_text="1箱あたりの入数", verbose_name="入数"
                    ),
                ),
                ("box_count", models.PositiveIntegerField(verbose_name="箱数")),
                (
                    "calculated_quantity",
                    models.PositiveIntegerField(
                        help_text="入数 × 箱数で自動計算", verbose_name="数量"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receiving_items",
                        to="purchases.purchaseorderitem",
                        verbose_name="発注明細",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receiving_items",
                        to="purchases.part",
                        verbose_name="部品",
                    ),
                ),
                (
                    "receiving",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchases.purchasereceiving",
                        verbose_name="受入確認",
                    ),
                ),
            ],
            options={
                "verbose_name": "購入品受入確認項目",
                "verbose_name_plural": "購入品受入確認項目一覧",
                "db_table": "purchase_receiving_items",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["order_number"], name="purchase_or_order_n_51aa62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["product", "status"], name="purchase_or_product_8868f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["supplier_branch", "status"],
                name="purchase_or_supplie_e8bb82_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["order_date"], name="purchase_or_order_d_409199_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["status"], name="purchase_or_status_5ac239_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorderitem",
            index=models.Index(
                fields=["purchase_order"], name="purchase_or_purchas_a61376_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorderitem",
            index=models.Index(fields=["part"], name="purchase_or_part_id_dbede6_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorderitem",
            index=models.Index(
                fields=["part_number"], name="purchase_or_part_nu_112305_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorderitem",
            index=models.Index(
                fields=["receiving_confirmed"], name="purchase_or_receivi_2f57c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorderitem",
            index=models.Index(
                fields=["count_confirmed"], name="purchase_or_count_c_0556eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorderitem",
            index=models.Index(
                fields=["purchase_order", "count_confirmed"],
                name="purchase_or_purchas_9c8f3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorderitem",
            index=models.Index(
                fields=["purchase_order", "receiving_confirmed"],
                name="purchase_or_purchas_32929d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchasediteminventory",
            index=models.Index(fields=["part"], name="purchased_i_part_id_b390e4_idx"),
        ),
        migrations.AddIndex(
            model_name="purchasediteminventory",
            index=models.Index(
                fields=["lot_number"], name="purchased_i_lot_num_db20e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasediteminventory",
            index=models.Index(
                fields=["received_date"], name="purchased_i_receive_29e613_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasediteminventory",
            index=models.Index(
                fields=["part", "received_date"], name="purchased_i_part_id_19af26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereceiving",
            index=models.Index(
                fields=["product"], name="purchase_re_product_e38825_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereceiving",
            index=models.Index(
                fields=["supplier_branch"], name="purchase_re_supplie_c1368a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereceiving",
            index=models.Index(fields=["status"], name="purchase_re_status_9fe740_idx"),
        ),
        migrations.AddIndex(
            model_name="purchasereceiving",
            index=models.Index(
                fields=["receiving_date"], name="purchase_re_receivi_a46729_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereceiving",
            index=models.Index(
                fields=["product", "status"], name="purchase_re_product_3e318f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereceivingitem",
            index=models.Index(
                fields=["receiving"], name="purchase_re_receivi_a691cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereceivingitem",
            index=models.Index(
                fields=["part_number"], name="purchase_re_part_nu_db6ec8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereceivingitem",
            index=models.Index(fields=["part"], name="purchase_re_part_id_d7c919_idx"),
        ),
        migrations.AddIndex(
            model_name="purchasereceivingitem",
            index=models.Index(
                fields=["receiving", "part_number"],
                name="purchase_re_receivi_2409e0_idx",
            ),
        ),
    ]
