# Generated by Django 5.2.7 on 2026-01-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0014_part_product_optional"),
        ("purchases", "0016_purchaseorder_purchaseorderitem_and_more"),
    ]

    operations = []
