# Generated by Django 5.2.7 on 2026-01-07 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0017_merge_20260103_2314"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="発注日"
            ),
        ),
        migrations.CreateModel(
            name="InventoryAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("supplied", "支給品"), ("purchased", "購入品")],
                        max_length=20,
                        verbose_name="在庫タイプ",
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[("increase", "増加"), ("decrease", "減少")],
                        max_length=20,
                        verbose_name="調整タイプ",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="調整数量")),
                (
                    "quantity_before",
                    models.PositiveIntegerField(verbose_name="調整前数量"),
                ),
                (
                    "quantity_after",
                    models.PositiveIntegerField(verbose_name="調整後数量"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("stocktaking", "棚卸"),
                            ("non_conformance", "不適合"),
                            ("damage", "破損"),
                            ("correction", "訂正"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        verbose_name="調整理由",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_inventory_adjustments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "purchased_item_inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="purchases.purchasediteminventory",
                        verbose_name="購入品在庫",
                    ),
                ),
                (
                    "supplied_item_inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="purchases.suppliediteminventory",
                        verbose_name="支給品在庫",
                    ),
                ),
            ],
            options={
                "verbose_name": "在庫調整",
                "verbose_name_plural": "在庫調整一覧",
                "db_table": "inventory_adjustments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["item_type"], name="inventory_a_item_ty_7800d3_idx"
                    ),
                    models.Index(
                        fields=["adjustment_type"],
                        name="inventory_a_adjustm_b52179_idx",
                    ),
                    models.Index(
                        fields=["reason"], name="inventory_a_reason_0de891_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="inventory_a_created_ebb387_idx"
                    ),
                    models.Index(
                        fields=["supplied_item_inventory"],
                        name="inventory_a_supplie_20f142_idx",
                    ),
                    models.Index(
                        fields=["purchased_item_inventory"],
                        name="inventory_a_purchas_f94205_idx",
                    ),
                ],
            },
        ),
    ]
