# Generated by Django 5.2.7 on 2025-11-08 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0002_alter_supplier_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suppliercontact",
            name="name_kana",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="担当者名（カナ）"
            ),
        ),
        migrations.AlterField(
            model_name="suppliercontact",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="電話番号は数字、ハイフン、プラス記号、括弧のみ使用可能です",
                        regex="^[0-9\\-\\+\\(\\)]+$",
                    )
                ],
                verbose_name="電話番号（直通）",
            ),
        ),
    ]
