# Generated by Django 5.2.7 on 2026-01-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0004_remove_supplier_notes_supplier_currency"),
        ("supplier", "0005_supplier_currency_supplier_notes"),
    ]

    operations = []
