# Generated by Django 5.2.7 on 2025-11-08 18:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_code",
                    models.CharField(
                        help_text="例: CS001",
                        max_length=50,
                        unique=True,
                        verbose_name="カスタマーコード",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="例: 株式会社ABC",
                        max_length=200,
                        unique=True,
                        verbose_name="企業名",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="ウェブサイト"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備考")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="取引中顧客かどうか",
                        verbose_name="有効",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "カスタマー",
                "verbose_name_plural": "カスタマー一覧",
                "db_table": "customers",
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch_code",
                    models.CharField(
                        help_text="例: HQ(本社), NAG(名古屋支店)",
                        max_length=50,
                        unique=True,
                        verbose_name="拠点コード",
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(
                        help_text="例: 本社, 名古屋支店, 岡崎工場",
                        max_length=200,
                        verbose_name="拠点名",
                    ),
                ),
                (
                    "branch_type",
                    models.CharField(
                        choices=[
                            ("HEAD_OFFICE", "本社"),
                            ("BRANCH", "支店"),
                            ("SALES_OFFICE", "営業所"),
                            ("FACTORY", "工場"),
                            ("WAREHOUSE", "倉庫"),
                            ("OTHER", "その他"),
                        ],
                        default="BRANCH",
                        max_length=20,
                        verbose_name="拠点種別",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="郵便番号"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="住所"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="電話番号は数字、ハイフン、プラス記号、括弧のみ使用可能です",
                                regex="^[0-9\\-\\+\\(\\)]+$",
                            )
                        ],
                        verbose_name="代表番号",
                    ),
                ),
                (
                    "fax_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="電話番号は数字、ハイフン、プラス記号、括弧のみ使用可能です",
                                regex="^[0-9\\-\\+\\(\\)]+$",
                            )
                        ],
                        verbose_name="FAX番号",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="代表メールアドレス",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="備考")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="customers.customer",
                        verbose_name="カスタマー",
                    ),
                ),
            ],
            options={
                "verbose_name": "カスタマー拠点",
                "verbose_name_plural": "カスタマー拠点一覧",
                "db_table": "customer_branches",
                "ordering": ["customer", "branch_type", "branch_name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="担当者名")),
                (
                    "name_kana",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="担当者名（カナ）",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="部署"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="役職"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="メールアドレス",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="電話番号は数字、ハイフン、プラス記号、括弧のみ使用可能です",
                                regex="^[0-9\\-\\+\\(\\)]+$",
                            )
                        ],
                        verbose_name="電話番号（直通）",
                    ),
                ),
                (
                    "extension_number",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="内線番号"
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="電話番号は数字、ハイフン、プラス記号、括弧のみ使用可能です",
                                regex="^[0-9\\-\\+\\(\\)]+$",
                            )
                        ],
                        verbose_name="携帯電話番号",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="customers.customerbranch",
                        verbose_name="所属拠点",
                    ),
                ),
            ],
            options={
                "verbose_name": "カスタマー担当者",
                "verbose_name_plural": "カスタマー担当者一覧",
                "db_table": "customer_contacts",
                "ordering": ["branch", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="customerbranch",
            constraint=models.UniqueConstraint(
                fields=("customer", "branch_name"), name="unique_customer_branch_name"
            ),
        ),
    ]
