# Generated by Django 5.2.7 on 2026-01-25 14:00

import api.imports.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("manufacturing", "0004_alter_manufacturingitem_production_type"),
        ("supplier", "0003_alter_suppliercontact_name_kana_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportPurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "po_number",
                    models.CharField(
                        help_text="輸入発注を識別する番号（自動生成）",
                        max_length=50,
                        unique=True,
                        verbose_name="PO番号",
                    ),
                ),
                (
                    "order_date",
                    models.DateField(
                        help_text="発注を行った日付", verbose_name="発注日"
                    ),
                ),
                (
                    "expected_ship_date",
                    models.DateField(
                        blank=True,
                        help_text="サプライヤーからの出荷予定日",
                        null=True,
                        verbose_name="出荷予定日",
                    ),
                ),
                (
                    "expected_arrival_date",
                    models.DateField(
                        blank=True,
                        help_text="日本への到着予定日",
                        null=True,
                        verbose_name="到着予定日",
                    ),
                ),
                (
                    "actual_ship_date",
                    models.DateField(blank=True, null=True, verbose_name="実出荷日"),
                ),
                (
                    "actual_arrival_date",
                    models.DateField(blank=True, null=True, verbose_name="実到着日"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("confirmed", "確定"),
                            ("shipped", "出荷済み"),
                            ("in_transit", "輸送中"),
                            ("arrived", "到着済み"),
                            ("completed", "完了"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="取引通貨（USD, EUR, CNY, JPY等）",
                        max_length=10,
                        verbose_name="通貨",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="発注時点の参考為替レート",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="為替レート",
                    ),
                ),
                (
                    "shipping_method",
                    models.CharField(
                        blank=True,
                        help_text="Air, Sea, Express等",
                        max_length=50,
                        verbose_name="輸送方法",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="追跡番号"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_import_pos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "supplier_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_purchase_orders",
                        to="supplier.supplierbranch",
                        verbose_name="サプライヤー支店",
                    ),
                ),
            ],
            options={
                "verbose_name": "輸入発注",
                "verbose_name_plural": "輸入発注一覧",
                "db_table": "import_purchase_orders",
                "ordering": ["-order_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="サプライヤーからのインボイス番号",
                        max_length=100,
                        verbose_name="インボイス番号",
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="インボイス日付")),
                (
                    "received_date",
                    models.DateField(
                        blank=True,
                        help_text="インボイスを受領した日付",
                        null=True,
                        verbose_name="受領日",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("pending", "処理待ち"),
                            ("processing", "処理中"),
                            ("completed", "完了"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="USD", max_length=10, verbose_name="通貨"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="小計",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="税額",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="送料",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="合計金額",
                    ),
                ),
                (
                    "registered_as_semi_finished",
                    models.BooleanField(
                        default=False,
                        help_text="このインボイスの品目が半製品として在庫登録されたかどうか",
                        verbose_name="半製品在庫登録済み",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_import_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "supplier_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_invoices",
                        to="supplier.supplierbranch",
                        verbose_name="サプライヤー支店",
                    ),
                ),
                (
                    "linked_pos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="invoices",
                        to="imports.importpurchaseorder",
                        verbose_name="紐付けPO",
                    ),
                ),
            ],
            options={
                "verbose_name": "インボイス",
                "verbose_name_plural": "インボイス一覧",
                "db_table": "import_invoices",
                "ordering": ["-invoice_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportPurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_number", models.CharField(max_length=100, verbose_name="品番")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="品名・説明"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="数量")),
                (
                    "unit",
                    models.CharField(default="個", max_length=20, verbose_name="単位"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="単価",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="金額",
                    ),
                ),
                (
                    "received_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="受入済み数量"),
                ),
                (
                    "is_received",
                    models.BooleanField(default=False, verbose_name="受入完了"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "import_po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="imports.importpurchaseorder",
                        verbose_name="輸入発注",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_po_items",
                        to="manufacturing.material",
                        verbose_name="材料",
                    ),
                ),
            ],
            options={
                "verbose_name": "輸入発注明細",
                "verbose_name_plural": "輸入発注明細一覧",
                "db_table": "import_purchase_order_items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ImportInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_number", models.CharField(max_length=100, verbose_name="品番")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="品名・説明"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="数量")),
                (
                    "unit",
                    models.CharField(default="個", max_length=20, verbose_name="単位"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="単価",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="金額",
                    ),
                ),
                (
                    "registered_as_semi_finished",
                    models.BooleanField(
                        default=False, verbose_name="半製品在庫登録済み"
                    ),
                ),
                (
                    "ocr_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="OCRによる抽出時の信頼度（0-1）",
                        max_digits=5,
                        null=True,
                        verbose_name="OCR信頼度",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "import_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="imports.importinvoice",
                        verbose_name="インボイス",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_invoice_items",
                        to="manufacturing.material",
                        verbose_name="材料",
                    ),
                ),
                (
                    "import_po_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_items",
                        to="imports.importpurchaseorderitem",
                        verbose_name="PO明細",
                    ),
                ),
            ],
            options={
                "verbose_name": "インボイス明細",
                "verbose_name_plural": "インボイス明細一覧",
                "db_table": "import_invoice_items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ImportFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("waybill", "Waybill"),
                            ("invoice", "Invoice"),
                            ("bill", "請求書"),
                            ("packing_list", "Packing List"),
                            ("certificate", "証明書"),
                            ("other", "その他"),
                        ],
                        default="invoice",
                        max_length=20,
                        verbose_name="ファイル種別",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=api.imports.models.import_file_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "bmp",
                                    "xlsx",
                                    "xls",
                                    "doc",
                                    "docx",
                                ]
                            )
                        ],
                        verbose_name="ファイル",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="元ファイル名"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ファイルサイズ"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="アップロード日時"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_import_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="アップロード者",
                    ),
                ),
                (
                    "import_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="imports.importinvoice",
                        verbose_name="インボイス",
                    ),
                ),
            ],
            options={
                "verbose_name": "インポートファイル",
                "verbose_name_plural": "インポートファイル一覧",
                "db_table": "import_files",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["import_invoice"], name="import_file_import__17e940_idx"
                    ),
                    models.Index(
                        fields=["file_type"], name="import_file_file_ty_d9aa95_idx"
                    ),
                    models.Index(
                        fields=["uploaded_at"], name="import_file_uploade_110234_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="importpurchaseorder",
            index=models.Index(
                fields=["po_number"], name="import_purc_po_numb_99f695_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importpurchaseorder",
            index=models.Index(
                fields=["supplier_branch"], name="import_purc_supplie_b62199_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importpurchaseorder",
            index=models.Index(fields=["status"], name="import_purc_status_9d8081_idx"),
        ),
        migrations.AddIndex(
            model_name="importpurchaseorder",
            index=models.Index(
                fields=["order_date"], name="import_purc_order_d_43b52d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importpurchaseorder",
            index=models.Index(
                fields=["expected_arrival_date"], name="import_purc_expecte_f0cb0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importpurchaseorder",
            index=models.Index(
                fields=["created_at"], name="import_purc_created_96e86a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importinvoice",
            index=models.Index(
                fields=["invoice_number"], name="import_invo_invoice_2b0e1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importinvoice",
            index=models.Index(
                fields=["supplier_branch"], name="import_invo_supplie_2eadab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importinvoice",
            index=models.Index(fields=["status"], name="import_invo_status_8338be_idx"),
        ),
        migrations.AddIndex(
            model_name="importinvoice",
            index=models.Index(
                fields=["invoice_date"], name="import_invo_invoice_e91812_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importinvoice",
            index=models.Index(
                fields=["received_date"], name="import_invo_receive_d4ec99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importinvoice",
            index=models.Index(
                fields=["created_at"], name="import_invo_created_e47872_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importpurchaseorderitem",
            index=models.Index(
                fields=["import_po"], name="import_purc_import__5a7f91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importpurchaseorderitem",
            index=models.Index(
                fields=["part_number"], name="import_purc_part_nu_d0821c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importpurchaseorderitem",
            index=models.Index(
                fields=["material"], name="import_purc_materia_a0ab52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importinvoiceitem",
            index=models.Index(
                fields=["import_invoice"], name="import_invo_import__1710ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importinvoiceitem",
            index=models.Index(
                fields=["part_number"], name="import_invo_part_nu_9cfbb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importinvoiceitem",
            index=models.Index(
                fields=["material"], name="import_invo_materia_5322bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importinvoiceitem",
            index=models.Index(
                fields=["import_po_item"], name="import_invo_import__09464e_idx"
            ),
        ),
    ]
