# Generated by Django 5.2.7 on 2026-01-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importinvoice",
            name="transportation_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Transportation Fee",
                max_digits=14,
                null=True,
                verbose_name="輸送費",
            ),
        ),
    ]
