# Generated by Django 5.2.7 on 2025-11-22 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference_type",
                    models.CharField(
                        choices=[
                            ("part_column_order", "部品一覧のカラム順序"),
                            ("parts_column_visibility", "部品一覧のカラム表示/非表示"),
                            ("products_column_order", "製品一覧のカラム順序"),
                        ],
                        max_length=50,
                        verbose_name="設定タイプ",
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        help_text="ユーザー設定をJSON形式で保存します。",
                        verbose_name="設定値",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー設定",
                "verbose_name_plural": "ユーザー設定一覧",
                "db_table": "user_preferences",
                "indexes": [
                    models.Index(
                        fields=["user", "preference_type"], name="user_pref_idx"
                    )
                ],
                "unique_together": {("user", "preference_type")},
            },
        ),
    ]
