# Generated by Django 5.2.7 on 2025-11-22 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="作成日時",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="preference_type",
            field=models.CharField(
                choices=[
                    ("parts_column_order", "部品一覧のカラム順序"),
                    ("parts_column_visibility", "部品一覧のカラム表示/非表示"),
                    ("products_column_order", "製品一覧のカラム順序"),
                    ("products_column_visibility", "製品一覧のカラム表示/非表示"),
                ],
                max_length=50,
                verbose_name="設定タイプ",
            ),
        ),
    ]
