# Generated by Django 5.2.7 on 2025-12-14 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userpreference_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        unique=True, verbose_name="IPアドレス"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="説明"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "許可IPアドレス",
                "verbose_name_plural": "許可IPアドレス一覧",
                "db_table": "allowed_ips",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IPRestrictionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False, verbose_name="IP制限を有効にする"
                    ),
                ),
                (
                    "exclude_superusers",
                    models.BooleanField(
                        default=True,
                        help_text="管理者権限を持つユーザーはIP制限の対象外にする",
                        verbose_name="管理者権限ユーザーを除外",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "IP制限設定",
                "verbose_name_plural": "IP制限設定",
                "db_table": "ip_restriction_settings",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="最終ログインIPアドレス"
            ),
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IPアドレス")),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, null=True, verbose_name="ユーザーエージェント"
                    ),
                ),
                (
                    "login_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="ログイン日時"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(default=True, verbose_name="ログイン成功"),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="失敗理由"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ログイン履歴",
                "verbose_name_plural": "ログイン履歴一覧",
                "db_table": "login_logs",
                "ordering": ["-login_at"],
            },
        ),
        migrations.DeleteModel(
            name="UserPreference",
        ),
    ]
