# Generated by Django 5.2.7 on 2025-12-15 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_allowedip_iprestrictionsettings_user_last_login_ip_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allowedip",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "グローバル許可IPアドレス",
                "verbose_name_plural": "グローバル許可IPアドレス一覧",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="ip_restriction_enabled",
            field=models.BooleanField(
                default=False,
                help_text="このユーザーに対してIPアドレス制限を適用する",
                verbose_name="IP制限を有効にする",
            ),
        ),
        migrations.CreateModel(
            name="UserAllowedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IPアドレス")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="説明"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "is_first_login_ip",
                    models.BooleanField(
                        default=False,
                        help_text="初回ログイン時のIPアドレス",
                        verbose_name="初回ログインIP",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_ips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー許可IPアドレス",
                "verbose_name_plural": "ユーザー許可IPアドレス一覧",
                "db_table": "user_allowed_ips",
                "ordering": ["-created_at"],
                "unique_together": {("user", "ip_address")},
            },
        ),
    ]
