# Generated by Django 5.2.7 on 2025-11-08 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="この製品を購入する顧客",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="customers.customer",
                verbose_name="顧客",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "有効"),
                    ("DISCONTINUED", "廃盤"),
                    ("DEVELOPMENT", "開発中"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="ステータス",
            ),
        ),
    ]
