# Generated by Django 5.2.7 on 2025-11-09 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("products", "0002_product_customer_alter_product_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="customer",
        ),
        migrations.AddField(
            model_name="product",
            name="customer_branch",
            field=models.ForeignKey(
                blank=True,
                help_text="この製品を購入する顧客拠点",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="customers.customerbranch",
                verbose_name="顧客拠点",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["customer_branch"], name="products_custome_940d55_idx"
            ),
        ),
    ]
