# Generated by Django 5.2.7 on 2025-12-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_model_info"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="product",
            new_name="products_model_i_26a2e4_idx",
            old_name="products_model_i_a1b2c3_idx",
        ),
    ]
