# Generated by Django 5.2.7 on 2026-01-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_is_assembly_product_is_parts_processing"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="product",
            new_name="products_is_asse_d91713_idx",
            old_name="products_is_asse_f8d9e2_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_is_part_3a87c5_idx",
            old_name="products_is_part_a3c4b1_idx",
        ),
    ]
